language: objective-c

osx_image: xcode9

install:
  - carthage bootstrap

deploy:
  provider: releases
  api_key: $GITHUB_ACCESS_TOKEN
  file: "Iris.framework.zip"
  skip_cleanup: true
  on:
    tags: true
    condition: -e "$TRAVIS_BUILD_DIR/Iris.framework.zip"

matrix:
  include:

    # iOS 9.3
    - script:
      - >-
        xcodebuild
        build-for-testing test-without-building
        -project Iris.xcodeproj
        -scheme Iris-iOS
        -sdk iphonesimulator
        -destination "platform=iOS Simulator,name=iPhone 6s,OS=9.3"
        -configuration Release

    # iOS 10.3
    - script:
      - >-
        xcodebuild
        build-for-testing test-without-building
        -project Iris.xcodeproj
        -scheme Iris-iOS
        -sdk iphonesimulator
        -destination "platform=iOS Simulator,name=iPhone 7,OS=10.3"
        -configuration Release

    # tvOS 9.0
    - script:
      - >-
        xcodebuild
        build-for-testing test-without-building
        -project Iris.xcodeproj
        -scheme Iris-tvOS
        -sdk appletvsimulator
        -destination "platform=tvOS Simulator,name=Apple TV 1080p,OS=9.0"
        -configuration Release

    # tvOS 10.2
    - script:
      - >-
        xcodebuild
        build-for-testing test-without-building
        -project Iris.xcodeproj
        -scheme Iris-tvOS
        -sdk appletvsimulator
        -destination "platform=tvOS Simulator,name=Apple TV 1080p,OS=10.2"
        -configuration Release

    # macOS
    - script:
      - >-
        xcodebuild
        build test
        -project Iris.xcodeproj
        -scheme Iris-macOS
        -sdk macosx
        -destination "arch=x86_64"
        -configuration Release

    # Carthage
    - script:
      - carthage build --no-skip-current
      - if [[ -n "$TRAVIS_TAG" ]]; then carthage archive Iris; fi

    # CocoaPods
    - script:
      - pod lib lint
